### ISSUE TITLE
Issue with example modes showing up in QGroundControl

### ISSUE THREAD

**Issue by AbhinavPeri** [Auterion/px4-ros2-interface-lib#17]
Going off the documentation from the PX4 docs, I have cloned this repository and built my workspace. However when I run the examples, I am not able to find the example modes in the QGroundControl Mode Selector. I can see that the node has registered the mode and that commander status recognizes the external mode. How do I get QGroundControl to show this. Alternatively, is there another way to run an external mode without using QGroundControl?

![image](https://github.com/Auterion/px4-ros2-interface-lib/assets/54607217/088ead66-6af2-469a-bd20-7ddb31048197)
![image](https://github.com/Auterion/px4-ros2-interface-lib/assets/54607217/08495738-9fc9-4fc3-8578-cb0ff26c4176)
![image](https://github.com/Auterion/px4-ros2-interface-lib/assets/54607217/dafac98d-8bfa-4d89-8fe4-c5f217397ddf)

**Comment by GuillaumeLaine** [comment]
Hi @AbhinavPeri thanks for raising the issue.
This is indeed a problem, in the meantime could you try again but launching QGC _after_ running the example mode? I've also had this issue with modes not showing up properly in the ground control system if the app was already open.

**Comment by AbhinavPeri** [comment]
I just tried it, and I still don't see the mode.

**Comment by PerFrivik** [comment]
Hey @AbhinavPeri, try to use the QGC [daily build ](https://docs.qgroundcontrol.com/master/en/qgc-user-guide/releases/daily_builds.html) as the stable release does not have the feature implemented yet, I am guessing. 

Let me know if its works :).

**Comment by AbhinavPeri** [comment]
@PerFrivik using the daily build looks like it fixed the issue. It's amazing how reinstalling software fixes so many problems. Thanks everyone for the help!

**Comment by Jaeyoung-Lim** [comment]
I can confirm that this is still a problem

**Comment by Kametor** [comment]
I also had a problem. If you cant open QGround Daily check this [QGroundControl Issue #9847](https://github.com/mavlink/qgroundcontrol/issues/9847).

**Comment by wly218** [comment]
Hey,@azerupi.May I ask if your problem has been solved?I also couldn't diplay the custom flight mode using either of the two versions

**Comment by dakejahl** [comment]
It's a bug in QGC, working on it here
https://github.com/mavlink/qgroundcontrol/pull/12581

**Comment by wly218** [comment]
OK，I see.Thank you!
