### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by tuananh0606-tech** [Auterion/px4-ros2-interface-lib#56]
![image](https://github.com/user-attachments/assets/d1362496-eca5-4d0e-a32e-c33067b3db1a)

I am trying to run the example, but I keep getting this error. I tried reinstalling PX4, but it still doesn't work. Please help me.

**Comment by GuillaumeLaine** [comment]
Hi @tuananh0606-tech you need to build px4-ros2-interface-lib with a version of the px4_msgs library that matches the message set of the PX4 you're using. This is what is meant in the README with: 

> Compatibility is only guaranteed if using latest `main` on the PX4 and px4_ros2/px4_msgs side

 What you can do is:
 - Check that you're using a PX4 version that has the same message set as [PX4/PX4-Autopilot:main](https://github.com/PX4/PX4-Autopilot/). This corresponds to the contents of the `msg/` directory, and can be checked using [this script](https://github.com/Auterion/px4-ros2-interface-lib/blob/main/scripts/check-message-compatibility.py).
 - Rebuild px4-ros2-interface-lib with the latest px4_msgs main. So build [PX4/px4_msgs:main](https://github.com/PX4/px4_msgs) locally, source it, and rebuild px4-ros2-interface-lib
 
 Hopefully this helps, let me know if it solves the problem
